### ISSUE TITLE
does this depends on specific toolboxes?

### ISSUE THREAD

**Issue by jeannotes** [aim-uofa/model-quantization#4]
this great work supports some tasks, like segmentation, detection, 
when it comes to detection, you mention that it supports facebook's detectron2, so my question is 
does this support mmdetection or any detections repos

**Comment by blueardour** [comment]
It does.

This repo re-implements some basic layers such as conv/fc/eltwise/etc.  with quantization support wrapped inside. It is possible to be integrated in any CNN-based frameworks. I have successed in integrating it  several github repos such as Detectron2/AdeleiDet/EDSR-pytorch. I did not try on mmdetection yet. You might have a try by replacing the coresponding layers in their framework.

**Comment by blueardour** [comment]
BTW. Support for transformer-based framework is on the way.

**Comment by jeannotes** [comment]
@blueardour amazing, this is great
